<?php
// $Id: popups_admin.module,v 1.1.4.7 2008/12/07 18:00:35 starbow Exp $

/**
 * @file
 * Uses the popups API to add some popups to admin pages.
 * 
 * @todo
 * Adding Javascript into popups doesn't always work.
 *   tabledrag onmouse up action.
 *   user.js and teaser.js bugs.
 * Taxonomy > Add vocab.  Adding second item to page does not trigger d-n-d transformation.
 *     Might be a problem with Taxonomy.  Menus doesn't have problem (adds d-n-d on first item).
 *
 */

/**
 * hook_popups
 * 
 * This implements hook_popups, defined in popups_get_popups.
 * It adds page-in-popup behavior to the core admin pages.
 * See the comments in popups_add_popups for explination of the options.
 *
 */
function popups_admin_popups() {
    
  return array(
    'admin/build/block' => array( // Blocks admin page.
      '#tabs-wrapper a[href$=admin/build/block/add]', // Add Block
      '#blocks a[href~=admin/build/block/configure]'  => array(  // configure
        'additionalJavascript' => array('misc/collapse.js'),
      ),
      '#blocks a[href~=admin/build/block/delete]', // delete
    ),
    'admin/build/path' => array( // URL aliases admin page.
      '#tabs-wrapper a[href$=admin/build/path/add]', // Add alias
      'td:nth-child(3) a[href~=admin/build/path/edit]', // edit alias
      'td:nth-child(4) a[href~=admin/build/path/delete]', // delete alias
    ),
    'admin/content/taxonomy' => array( // Taxonomy admin page.
      // TODO: If there are not more than one items to start with, d-n-d files aren't loaded into page.
      // This causes trouble when the 2nd item is added, no d-n-d.
      // Might be bug in taxonomy table building (or at least inconsistancy).
      '#tabs-wrapper a[href$=admin/content/taxonomy/add/vocabulary]' => array( // Add vocabulary
        'additionalJavascript' => array('misc/tabledrag.js'),
      ),       
      '#taxonomy-overview-vocabularies td a:contains('. t('edit vocabulary') .')', // edit vocabulary
      '#taxonomy-overview-vocabularies td a:contains('. t('list terms') .')' => array( // list terms
        'noUpdate' => TRUE,
        'additionalJavascript' => array('misc/tabledrag.js'),
      ),
      '#taxonomy-overview-vocabularies td a:contains('. t('add terms') .')' => array(  // add terms
        'noUpdate' => TRUE,
        'additionalJavascript' => array('misc/collapse.js'),
      ),
    ),
    'admin/content/types' => array( // Content Type admin page
      '#tabs-wrapper a[href$=admin/content/types/add]' => array(  // Add content type
        'additionalJavascript' => array('misc/collapse.js'),
      ),
      'table td:nth-child(4) a, table td:nth-child(5) a, table td:nth-child(7) a' // edit, add field, delete
    ),
    'admin/content/types/list' => array( // Content Type admin page
      '#tabs-wrapper a[href$=admin/content/types/add]' => array(  // Add content type
        'additionalJavascript' => array('misc/collapse.js'),
      ),
      'table td:nth-child(4) a, table td:nth-child(5) a, table td:nth-child(7) a' // edit, add field, delete
    ),
    'admin/content/node' => array( // Existing Content admin page
      '#node-admin-content td a:contains('. t('edit') .')' => array( // edit
        'additionalJavascript' => array('misc/collapse.js'),
        // TODO: teaser.js not working: Drupal.settings.teaser has no properties
        // 'additionalJavascript' => array('misc/collapse.js', 'misc/teaser.js'),
      )      
    ),
    'page_node_form' => array( // Node edit form
      'a[href$=filter/tips]' => array( // Fixes insane "More information..." link
        'noUpdate' => TRUE,
        //TODO 'addCloseButton' => TRUE - just an idea.
      )      
    ),
    'admin/content/comment' => array( // Comments admin page.
      'table td:nth-child(2) a' => array( // view (TODO: popup too small)
        'noUpdate' => TRUE,
        'additionalCss' => array(), //TODO: needs some custom css to get #comments to stay in the popup (no -25px margin).
      ),
      '#comment-admin-overview td a:contains('. t('edit') .')' => array( // edit
        'additionalJavascript' => array('misc/collapse.js'),
      ),
    ),
    'admin/user/rules' => array( // Access rules admin page.
      '#tabs-wrapper a[href$=admin/user/rules/add]', // Add rule
      'table td:nth-child(4) a, table td:nth-child(5) a', // edit, delete
      '#tabs-wrapper a[href$=/admin/user/rules/check]' => array( // Check rule 
        'noUpdate' => TRUE,
      ),
    ),
    'admin/user/user' => array( // Manage all users admin page.
      //Add user (TODO: Can't test, keeps crashing apache!)
      '#tabs-wrapper a[href$=admin/user/user/create]' => array(
        // TODO: "translate has no properties" user.js line 16.
        'additionalJavascript' => array(drupal_get_path('module', 'user') .'/user.js'),
      ),
      '#user-admin-account td:nth-child(2) a' => array( // View the user
        'noUpdate' => TRUE,
      ),
      
    ),
    'menu_overview_form' => array( // Menu admin form.
      // Add Item, , edit, delete
      '#tabs-wrapper a:eq(1), table#menu-overview td:nth-child(5) a, table#menu-overview td:nth-child(6) a',
      '#tabs-wrapper a:eq(2)' => array( // Edit menu: update just page title.
        'updateTitle' => TRUE,
        'noUpdate' => TRUE,
      ),
    ),
    
//    // CCK - Manage fields page.
//    'content_admin_field_overview_form' => array( 
//      'div#tabs-wrapper a:eq(0)' => array( // Edit - ISSUE: returns to different page.
//        'updateTitle' => TRUE,
//        'noUpdate' => TRUE,
//        'additionalJavascript' => array('misc/collapse.js'),
//        'forceReturn' => 'admin/content', // If workflow goes to 'admin/content', treat it as success. 
//      ),
//      'div#tabs-wrapper a:eq(2)' => array( // Display fields
//        'noUpdate' => TRUE,
//      ),
//      'div#tabs-wrapper a:eq(3), div#tabs-wrapper a:eq(4)', // Add field, Add group
//      'table td:nth-child(5) a' => array( // configure 
//        'singleRow' => array( 'td:eq(0)' ), // Just update the row (still expiremental).
//      ),
//      'table td:nth-child(6) a', //  remove
//    ),
//
//    // Trouble?
//    'node/*' => array(
//      '.comment_add a:contains('. t('Add new comment') .')', // Add comment.
//    ),
    
    
  );
}


