<?php
/* double-commented to avoid conflict with svn
// $Id: lookup_services.inc,v 1.1.2.3 2008/10/30 16:08:47 dman Exp $ 
*/
 
/**
 * @file A list of known lookup services and a brief description of their syntax
 * 
 * Remote lookup servers may be web services invoked directly through URL
 * arguments or more advanced XML/RPC type interfaces.
 * 
 * Currently only simple URL patterns are supported
 */
 
  